name: Test
on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
      env:
        SHELLCHECK_OPTS: -e SC2317
